# Gradle args
org.gradle.daemon   = false
org.gradle.jvmargs  = -Xmx4G
org.gradle.parallel = true
org.gradle.caching  = true

systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=10809
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=10809

# Versions
fabric_versions   = 1.21.1,1.21.11
neoforge_versions = 1.21.1,1.21.11

# Mod info
mod_id          = ui_layout
mod_name        = UI-Layout
mod_version     = 0.1a
mod_description = Mod description
mod_authors     = _BENDY659_
mod_license     = All Right Reversed
mod_group       = ru.benos

# Kotlin
kotlin_version = 2.2.0