# Gradle args
org.gradle.daemon   = false
org.gradle.jvmargs  = -Xmx4G
org.gradle.parallel = true
org.gradle.caching  = true

systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=10809
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=10809

# Versions
minecraft_version       = 1.21.1
fabric_loader_version   = 0.19.2
fabric_api_version      = 0.116.11
neoforge_loader_version = 21.1.26

fabric_kotlin_language_version = 1.13.7+kotlin.2.2.21
kotlin_for_forge_version       = 5.11.0

# Mod info
mod_id          = bos_ui_layout
mod_name        = BOS: UI-Layout
mod_version     = 0.1.5a
mod_description = Simple UI tool for making powerful Minecraft GUI
mod_authors     = _BENDY659_
mod_license     = All Right Reversed
mod_group       = ru.benos.libs

prefix_class_name = BosUiLayout

# Kotlin
kotlin_version = 2.2.21