# Gradle args
org.gradle.daemon   = false
org.gradle.jvmargs  = -Xmx4G
org.gradle.parallel = true
org.gradle.caching  = true

systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=10809
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=10809

# Versions
fabric_versions   = 1.21.1,1.21.11
neoforge_versions = 1.21.1,1.21.11

# Mod info
mod_id          = example_mod
mod_name        = Example mod
mod_version     = 1.0
mod_description = Mod description
mod_authors     = _BENDY659_
mod_license     = MIT
mod_group       = com.example

# Kotlin
kotlin_version = 2.0.21